### ISSUE TITLE
Deploy as debian package

### ISSUE THREAD

**Issue by orzechow** [KIT-MRT/util_caching#8]
Inspired by https://github.com/KIT-MRT/arbitration_graphs/issues/65, let's 

- [x] setup CPack for util_caching and 
- [x] deploy util_caching as debian package (via GitHub Action asset)

**Comment by orzechow** [comment]
@ll-nick Should we install util_caching into `/opt` instead of `/usr` etc?
There are various opinions on this (e.g. this [unix stackexchange answer](https://unix.stackexchange.com/questions/11544/what-is-the-difference-between-opt-and-usr-local/11552#11552)).

The main point against `/usr` IMHO is, that is suggests the package is deployed via a package manager like apt – which is not the case here.

Btw: In an attempt to fix the install directory of the arbitration_graphs GUI (consistent between tar.gz and deb package), I changed the install directory to `/opt` there.
Thus, I'd prefer to do that here as well, too

**Comment by orzechow** [comment]
Yikes… I just figured that the `/opt` install of arbitration graphs is off…

https://github.com/KIT-MRT/arbitration_graphs/pull/70#issuecomment-2465025433

**Comment by ll-nick** [comment]
I don't have a strong opinion on that. `/opt` does not seem right but that's a pure gut feeling.

Right now, the deb package is not being installed via a package manager but what if one day it is (e.g. via a ppa). Would you then change the install structure?

It seems like you opted for `/usr` now which is totally fine for me :+1:
